langauge: ruby
sudo: false
cache: bundler

branches:
  only: master

script: bundle exec ruby compatibility_test.rb && bundle exec ruby benchmark2.rb

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

gemfile:
  - gemfiles/4.1.16.gemfile
  - gemfiles/4.2.8.gemfile
  - gemfiles/5.0.2.gemfile

matrix:
  fast_finish: true
